samples: samples.tsv
units: units.tsv

params:
  general:
    end1_suffix: "_1"
    end2_suffix: "_2"
    alignment_quality: "10"
    temp_dir:
      gadi: ""
      shiny: "~/temp"
    runTable:
      PRJNA336352:
        file: 'PRJNA336352_SraRunTable.txt'
        selected_columns: ['Cell_Line', 'aggregate_column', 'Run']
        aggregate_column: 'chip_antibody'
        chip_input_value: 'none'

  bowtie2:
    cli_params_global: "--very-sensitive --end-to-end"
    index:
      gadi: "/g/data/kv78/References/Genomes/Homo_sapiens/GRCh37_hg19_UCSC/GRCh37_hg19_UCSC_canonical"
      shiny: "/Data/References/Genomes/Homo_sapiens/GRCh37_hg19_UCSC/GRCh37_hg19_UCSC_canonical"
  fastp: ""
