samples: samples.tsv
units: units.tsv

params:
  general:
    end1_suffix: "_1"
    end2_suffix: "_2"
    alignment_quality: "10"
    temp_dir:
      gadi: ""
      shiny: "~/temp"
    runTable:
      PRJNA336352:
        file: 'PRJNA336352_SraRunTable.txt'
        selected_columns: ['Cell_Line', 'aggregate_column', 'Run']
        aggregate_column: 'chip_antibody'
        chip_input_value: 'none'

  bowtie2:
    cli_params_global: "--very-sensitive --end-to-end"
    index:
      gadi: "/g/data/kv78/References/Genomes/Homo_sapiens/GRCh37_hg19_UCSC/GRCh37_hg19_UCSC_canonical"
      shiny: "/Data/References/Genomes/Homo_sapiens/GRCh37_hg19_UCSC/GRCh37_hg19_UCSC_canonical"
  fastp: ""

  deeptools:
    annotation_dir:
      gadi: '/home/150/sxk150/data/PromoterSeqCap/annotations/'
    genome_size:
      GRCh37_hg19_UCSC: 2864785220
    binSize : 30
    smoothLength : 10
    normalizeUsing : 'RPKM'
    referencePoint: 'center'
    beforeRegionStartLength : 1000
    afterRegionStartLength: 1000
    sortRegions : 'keep'
    plotProfile:
      numPlotsPerRow : 1
      colors: ['#FF0000FF' '#FFDB00FF' '#49FF00FF' '#00FF92FF' '#0092FFFF' '#4900FFFF' '#FF00DBFF']
    regionsFiles:
      Fig1A: ['Fig1A_cluster_1.bed', 'Fig1A_cluster_2.bed', 'Fig1A_cluster_3.bed', 'Fig1A_cluster_4.bed', 'Fig1A_cluster_5.bed', 'Fig1A_cluster_6.bed', 'Fig1A_cluster_7.bed']
      Fig1B: ['Fig1B_cluster_1.bed', 'Fig1B_cluster_2.bed', 'Fig1B_cluster_3.bed', 'Fig1B_cluster_4.bed', 'Fig1B_cluster_5.bed', 'Fig1B_cluster_6.bed', 'Fig1B_cluster_7.bed']
      Fig1C: ['Fig1C_cluster_1.bed', 'Fig1C_cluster_2.bed', 'Fig1C_cluster_3.bed', 'Fig1C_cluster_4.bed', 'Fig1C_cluster_5.bed', 'Fig1C_cluster_6.bed', 'Fig1C_cluster_7.bed']
      Fig1D: ['Fig1D_cluster_1.bed', 'Fig1D_cluster_2.bed', 'Fig1D_cluster_3.bed', 'Fig1D_cluster_4.bed', 'Fig1D_cluster_5.bed', 'Fig1D_cluster_6.bed', 'Fig1D_cluster_7.bed']
